stages:
  - config
  - build
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

set_dev:
  stage: config
  tags:
    - shell
  script:
    - echo "export API_HOST=apidev.zaplatisto.ru" > envfile

  artifacts:
    paths:
      - envfile
  only:
    - dev

set_prod:
  stage: config
  tags:
    - shell
  script:
    - echo "export API_HOST=api.zaplatisto.ru" > envfile

  artifacts:
    paths:
      - envfile
  only:
    - master

build-backend-dev:
  stage: build
  tags:
    - shell
  script:
    - echo "ENV NODE_ENV=production" >> Dockerfile
    - echo "ENV SERVICE_HOST=localhost" >> Dockerfile
    - echo "ENV JWT_SECRET=$JWT_SECRET" >> Dockerfile
    - echo "ENV EXPIRES_IN=$EXPIRES_IN" >> Dockerfile
    - echo "ENV SERVICE_PORT=$SERVICE_PORT" >> Dockerfile
    - echo "ENV SEQUELIZE_USER=$SEQUELIZE_USER" >> Dockerfile
    - echo "ENV SEQUELIZE_PASS=$SEQUELIZE_PASS" >> Dockerfile
    - echo "ENV SEQUELIZE_DB=$SEQUELIZE_DB" >> Dockerfile
    - echo "ENV SEQUELIZE_HOST=$SEQUELIZE_HOST" >> Dockerfile
    - echo "ENV SEQUELIZE_PORT=$SEQUELIZE_PORT" >> Dockerfile
    - sed -i "s/https:\/\/gitlab.zaplatisto.ru/https:\/\/gitlab-ci-token:$CI_JOB_TOKEN@gitlab.zaplatisto.ru/g" package.json
    - docker build --pull -f Dockerfile -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - docker image rm $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
  only:
    - dev

deploy_dev:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $DEV_USER@$DEV_HOST docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - ssh $DEV_USER@$DEV_HOST docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - ssh $DEV_USER@$DEV_HOST docker container rm -f dev_backend || true
    - ssh $DEV_USER@$DEV_HOST docker run -d -p $SERVICE_PORT:$SERVICE_PORT/tcp --name dev_backend $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
  only:
    - dev

deploy_prod:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $DEV_USER@$DEV_HOST docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - ssh $DEV_USER@$DEV_HOST docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - ssh $DEV_USER@$DEV_HOST docker container rm -f prod_front || true
    - ssh $DEV_USER@$DEV_HOST docker run -d -p $SERVICE_PORT:$SERVICE_PORT/tcp --name prod_front $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
  only:
    - prod
