stages:
  - build
  - deploy

variables:
  DOCKER_COMPOSE: docker/docker-compose.yml
  DOCKER_IMAGE_NAME: backend_${CI_COMMIT_REF_SLUG}
  DOCKER_FILE: docker/Dockerfile

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

build_dev:
  stage: build
  tags:
    - shell
  script:
    - echo "NODE_ENV=prod" >> .env
    - echo "SERVICE_HOST=localhost" >> .env
    - echo "JWT_SECRET=$JWT_SECRET" >> .env
    - echo "EXPIRES_IN=$EXPIRES_IN" >> .env
    - echo "SERVICE_PORT=$SERVICE_PORT" >> .env
    - echo "SEQUELIZE_USER=$SEQUELIZE_USER" >> .env
    - echo "SEQUELIZE_PASS=$SEQUELIZE_PASS" >> .env
    - echo "SEQUELIZE_DB=$SEQUELIZE_DB" >> .env
    - echo "SEQUELIZE_HOST=$SEQUELIZE_HOST" >> .env
    - echo "SEQUELIZE_PORT=$SEQUELIZE_PORT" >> .env
    - sed -i "s/https:\/\/gitlab.zaplatisto.ru/https:\/\/gitlab-ci-token:$CI_JOB_TOKEN@gitlab.zaplatisto.ru/g" package.json
    - docker-compose -p ${DOCKER_IMAGE_NAME} -f ${DOCKER_COMPOSE} build
    - docker-compose -p ${DOCKER_IMAGE_NAME} -f ${DOCKER_COMPOSE} push
  only:
    - dev

deploy_dev:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $DEV_USER@$DEV_HOST docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - ssh $DEV_USER@$DEV_HOST docker --file ${DOCKER_COMPOSE} pull 
    - ssh $DEV_USER@$DEV_HOST docker --file ${DOCKER_COMPOSE} down || true
    - ssh $DEV_USER@$DEV_HOST docker --file ${DOCKER_COMPOSE} up -d
  only:
    - dev

deploy_prod:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $DEV_USER@$DEV_HOST docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - ssh $DEV_USER@$DEV_HOST docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - ssh $DEV_USER@$DEV_HOST docker container rm -f prod_front || true
    - ssh $DEV_USER@$DEV_HOST docker run -d -p $SERVICE_PORT:$SERVICE_PORT/tcp --name prod_front $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
  only:
    - prod
