version: '3.6'

services:
  app:
    container_name: app-$CI_PIPELINE_ID
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    ports:
        - 127.0.0.1:3000:3000
    depends_on:
      - database

  database:
    container_name: database-$CI_PIPELINE_ID
    image: mariadb:10.7
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEQUELIZE_PASS}
      - MYSQL_PASSWORD=${SEQUELIZE_PASS}
      - MYSQL_USER=${SEQUELIZE_USER}
      - MYSQL_DATABASE=${SEQUELIZE_DB}